In [1]:
%%capture
from pathlib import Path

if Path.cwd().stem == "notebooks":
    %cd ..
    %load_ext autoreload
    %autoreload 2

In [34]:
import os
from pathlib import Path

import altair as alt
import holoviews as hv
import numpy as np
import polars as pl
import tomllib
from dotenv import load_dotenv
from polars import col

from src.data.database_manager import DatabaseManager
from src.experiments.measurement.stimulus_generator import StimulusGenerator
from src.features.scaling import scale_min_max
from src.features.utils import to_describe
from src.log_config import configure_logging
from src.plots.sci_data import (
    plot_stimulus_seed_grid,
    plot_stimulus_with_labels,
    plot_stimulus_with_physiological_signals,
)
from src.plots.utils import calculate_z_score

load_dotenv()
FIGURE_DIR = Path(os.getenv("SCI_DATA_FIGURE_DIR"))

configure_logging(
    ignore_libs=("Comm", "bokeh", "tornado", "matplotlib"),
)

pl.Config.set_tbl_rows(12)  # for 12 seeds
hv.output(widget_location="bottom", size=150)

In [35]:
db = DatabaseManager()

In [36]:
with db:
    df = db.get_trials("Explore_Data", exclude_problematic=True)

df = df.rename({"rating": "pain_rating", "pupil": "pupil_diameter"})

df = scale_min_max(
    df,
    exclude_additional_columns=[
        # already normalized:
        "temperature",
        "pain_rating",
        "brow_furrow",
        "cheek_raise",
        "mouth_open",
        "upper_lip_raise",
        "nose_wrinkle",
    ],
)

In [37]:
width = 800
height = 400

## Curve with physiological signals and confidence intervals

In [38]:
signals = [
    "temperature",
    "pain_rating",
    "pupil_diameter",
    "eda_tonic",
    "eda_phasic",
    "heart_rate",
    "mouth_open",
]

confidence_level = 0.95
z_score = calculate_z_score(confidence_level)

df = df.filter(col("stimulus_seed") == 133)

# Group by stimulus seed and normalized timestamp, then calculate mean, std, sem, ci
ci_values = (
    df.group_by(col("normalized_timestamp"), maintain_order=True)
    .agg(
        *[col(c).mean().alias(f"mean_{c}") for c in signals],
        *[col(c).std().alias(f"std_{c}") for c in signals],
        pl.len().alias("n"),
    )
    .sort("normalized_timestamp")
    .with_columns(
        *[(col(f"std_{c}") / col("n").sqrt()).alias(f"sem_{c}") for c in signals],
    )
    .with_columns(
        *[
            (col(f"mean_{c}") - z_score * col(f"sem_{c}")).alias(f"ci_lower_{c}")
            for c in signals
        ],
        *[
            (col(f"mean_{c}") + z_score * col(f"sem_{c}")).alias(f"ci_upper_{c}")
            for c in signals
        ],
    )
)

In [39]:
ci_values

shape: (1_801, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ normalize ┆ mean_temp ┆ mean_pain ┆ mean_pupi ┆ … ┆ ci_upper_ ┆ ci_upper_ ┆ ci_upper_ ┆ ci_upper │
│ d_timesta ┆ erature   ┆ _rating   ┆ l_diamete ┆   ┆ eda_tonic ┆ eda_phasi ┆ heart_rat ┆ _mouth_o │
│ mp        ┆ ---       ┆ ---       ┆ r         ┆   ┆ ---       ┆ c         ┆ e         ┆ pen      │
│ ---       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆           ┆           ┆ f64       ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0       ┆ 0.0       ┆ 0.36777   ┆ 0.817986  ┆ … ┆ 0.897999  ┆ 0.520724  ┆ 0.758764  ┆ 0.112443 │
│ 100.0     ┆ 0.000184  ┆ 0.380709  ┆ 0.815849  ┆ … ┆ 0.898871  ┆ 0.531165  ┆ 0.773526  ┆ 0.112933 │
│ 200.0     ┆ 0.000784  ┆ 0.400342  ┆ 0.81457   ┆ … ┆ 0.899673  ┆ 0.548329  ┆ 0.785095  ┆ 0.113939 │
│ 300.0     ┆ 0.001871  ┆ 0.419517  ┆ 0.811261  ┆ … ┆ 0.900439  ┆ 0.567504  ┆ 0.793923  ┆ 0.114631 │
│ 400.0     ┆ 0.003444  ┆ 0.43083   ┆ 0.805903  ┆ … ┆ 0.901228  ┆ 0.592282  ┆ 0.800592  ┆ 0.115327 │
│ 500.0     ┆ 0.005515  ┆ 0.443373  ┆ 0.802354  ┆ … ┆ 0.90196   ┆ 0.617684  ┆ 0.803857  ┆ 0.115728 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 179500.0  ┆ 0.158899  ┆ 0.484589  ┆ 0.355889  ┆ … ┆ 0.258447  ┆ 0.489626  ┆ 0.576842  ┆ 0.080445 │
│ 179600.0  ┆ 0.157452  ┆ 0.471173  ┆ 0.355701  ┆ … ┆ 0.259775  ┆ 0.485348  ┆ 0.576882  ┆ 0.080734 │
│ 179700.0  ┆ 0.1564    ┆ 0.454375  ┆ 0.355044  ┆ … ┆ 0.261231  ┆ 0.478451  ┆ 0.575466  ┆ 0.080965 │
│ 179800.0  ┆ 0.155739  ┆ 0.442525  ┆ 0.355616  ┆ … ┆ 0.262626  ┆ 0.473042  ┆ 0.573378  ┆ 0.081169 │
│ 179900.0  ┆ 0.155472  ┆ 0.429743  ┆ 0.355866  ┆ … ┆ 0.264101  ┆ 0.465355  ┆ 0.5706    ┆ 0.081448 │
│ 180000.0  ┆ 0.155438  ┆ 0.417037  ┆ 0.351818  ┆ … ┆ 0.265002  ┆ 0.458719  ┆ 0.5697    ┆ 0.081652 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [42]:
phy = plot_stimulus_with_physiological_signals(
    ci_values,
    signals,
    width=width,
    height=height,
)
phy.save(FIGURE_DIR / "stimulus_with_physiological_signals_ci.svg")
phy

alt.LayerChart(...)

## Curve with temperature intervals

In [56]:
def load_configuration(file_path: str) -> dict:
    """Load configuration from a TOML file."""
    file_path = Path(file_path)
    with open(file_path, "rb") as file:
        return tomllib.load(file)


config = load_configuration("src/experiments/measurement/measurement_config.toml")[
    "stimulus"
]

dummy_participant = {
    "temperature_baseline": 44.0,
    "temperature_range": 4,  # VAS 0 - VAS 70
}
config.update(dummy_participant)

stimulus = StimulusGenerator(config, seed=133)

In [55]:
lab = plot_stimulus_with_labels(
    stimulus,
    width=width,
    height=height,
)
lab.save(FIGURE_DIR / "stimulus_with_labels_ci.svg")
lab

alt.LayerChart(...)

## All curves

In [11]:
config["sample_rate"] = 2

stimuli = pl.concat(
    [
        pl.DataFrame(
            {
                "y": StimulusGenerator(config, seed).y,
                "time": np.arange(len(StimulusGenerator(config, seed).y)),
                "seed": np.array([seed] * len(StimulusGenerator(config, seed).y)),
            }
        )
        for seed in config["seeds"]
    ]
)
stimuli.group_by("seed", maintain_order=True).agg(to_describe("y"))

shape: (12, 10)
┌──────┬─────────┬──────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ seed ┆ y_count ┆ y_null_count ┆ y_mean    ┆ … ┆ y_25%     ┆ y_50%     ┆ y_75%     ┆ y_max     │
│ ---  ┆ ---     ┆ ---          ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64  ┆ u32     ┆ u32          ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════╪═════════╪══════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 133  ┆ 360     ┆ 0            ┆ 43.784518 ┆ … ┆ 42.979949 ┆ 43.455472 ┆ 44.640197 ┆ 45.990678 │
│ 243  ┆ 360     ┆ 0            ┆ 43.835698 ┆ … ┆ 43.001099 ┆ 43.8487   ┆ 44.741317 ┆ 45.969692 │
│ 265  ┆ 360     ┆ 0            ┆ 43.858845 ┆ … ┆ 42.905532 ┆ 43.851603 ┆ 44.774859 ┆ 45.984994 │
│ 396  ┆ 360     ┆ 0            ┆ 43.955609 ┆ … ┆ 43.269657 ┆ 43.88023  ┆ 44.825056 ┆ 45.951559 │
│ 467  ┆ 360     ┆ 0            ┆ 43.900993 ┆ … ┆ 43.147233 ┆ 43.829296 ┆ 44.782912 ┆ 45.966138 │
│ 658  ┆ 360     ┆ 0            ┆ 43.90003  ┆ … ┆ 42.969628 ┆ 43.911083 ┆ 44.71232  ┆ 45.878865 │
│ 681  ┆ 360     ┆ 0            ┆ 43.794    ┆ … ┆ 42.962248 ┆ 43.69888  ┆ 44.653396 ┆ 45.972101 │
│ 743  ┆ 360     ┆ 0            ┆ 43.912674 ┆ … ┆ 43.222426 ┆ 43.832328 ┆ 44.77548  ┆ 45.969461 │
│ 806  ┆ 360     ┆ 0            ┆ 43.761186 ┆ … ┆ 42.743569 ┆ 43.757714 ┆ 44.662761 ┆ 45.998058 │
│ 841  ┆ 360     ┆ 0            ┆ 43.953794 ┆ … ┆ 43.065676 ┆ 43.948205 ┆ 44.985134 ┆ 45.936935 │
│ 870  ┆ 360     ┆ 0            ┆ 43.862324 ┆ … ┆ 43.053088 ┆ 43.469542 ┆ 44.960941 ┆ 45.998662 │
│ 952  ┆ 360     ┆ 0            ┆ 43.965169 ┆ … ┆ 43.207087 ┆ 43.927739 ┆ 44.873823 ┆ 45.963827 │
└──────┴─────────┴──────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
# fig.savefig(FIGURE_DIR / "stimulus_seeds.png", dpi=300)

In [45]:
chart = plot_stimulus_seed_grid(stimuli, columns=3, width=260, height=150)
chart = chart.configure_header(labelFontSize=15)
chart.save(FIGURE_DIR / "stimulus_seed_grid.svg")
chart

alt.FacetChart(...)